// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: C:/Users/oscar/Desktop/Git/Proyecto1-Compiladores1/Aplicacion-Proyecto1-Compiladores1/src/main/java/reporte/ciclo/lexerCiclo.flex

package reporte.ciclo;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import reporte.ciclo.Simbolos;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class LexerCiclo implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\u10fe\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\3\22\0\1\4\1\0"+
    "\1\5\1\0\1\6\3\0\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\7\17"+
    "\1\22\1\23\1\24\1\25\1\26\2\0\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\2\35"+
    "\1\40\1\41\1\42\1\43\1\44\1\35\1\45\1\46"+
    "\1\47\1\50\1\51\1\35\1\52\2\35\1\53\1\0"+
    "\1\54\1\0\1\35\1\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\2\35\1\40\1\41"+
    "\1\42\1\43\1\44\1\35\1\45\1\46\1\47\1\50"+
    "\1\51\1\35\1\52\2\35\265\0\2\55\115\0\1\56"+
    "\u0180\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[768];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\4\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\15\21\1\22\1\23\2\1\1\0\1\24"+
    "\1\0\1\25\1\0\1\26\1\27\3\21\1\30\1\31"+
    "\7\21\1\32\1\21\1\33\1\21\1\34\1\0\1\21"+
    "\3\0\1\35\4\21\1\0\4\21\1\0\4\21\1\0"+
    "\1\21\1\0\1\21\1\0\3\21\1\0\4\21\1\0"+
    "\3\21\2\36\1\21\2\0\1\21\1\0\2\21\1\0"+
    "\1\21\1\0\4\21\1\0\1\37\1\40\1\41\1\21"+
    "\1\0\1\37\2\42\2\21\1\0\2\43\1\21\1\44"+
    "\1\21\2\45\1\21\1\0\1\21\2\46\2\47\2\21"+
    "\1\0\3\21\1\0\1\21\1\0\1\21\2\50\1\21"+
    "\1\0\2\51\2\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\57\0\57"+
    "\0\u0178\0\57\0\57\0\u01a7\0\57\0\57\0\u01d6\0\u0205"+
    "\0\u0234\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d"+
    "\0\u03ac\0\u03db\0\u040a\0\57\0\57\0\u0439\0\u0468\0\u011a"+
    "\0\57\0\u0497\0\57\0\u04c6\0\57\0\u01d6\0\u04f5\0\u0524"+
    "\0\u0553\0\u01d6\0\u01d6\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e"+
    "\0\u066d\0\u069c\0\u01d6\0\u06cb\0\u01d6\0\u06fa\0\u01d6\0\u0729"+
    "\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u04c6\0\u0814\0\u0843\0\u0872"+
    "\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea"+
    "\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62"+
    "\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda"+
    "\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u01d6\0\57\0\u0dc5\0\u0df4"+
    "\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c"+
    "\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u01d6\0\u01d6\0\u01d6"+
    "\0\u1086\0\u10b5\0\57\0\u01d6\0\57\0\u10e4\0\u1113\0\u1142"+
    "\0\u01d6\0\57\0\u1171\0\u01d6\0\u11a0\0\u01d6\0\57\0\u11cf"+
    "\0\u11fe\0\u122d\0\u01d6\0\57\0\u01d6\0\57\0\u125c\0\u128b"+
    "\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u1376\0\u13a5\0\u13d4\0\u1403"+
    "\0\u01d6\0\57\0\u1432\0\u1461\0\u01d6\0\57\0\u01d6\0\57";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\3\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\2\27\1\32\1\27\1\33\1\34\1\27\1\35\1\36"+
    "\1\27\1\37\1\40\1\41\1\42\1\27\1\43\1\27"+
    "\1\44\1\45\1\46\1\47\60\0\1\3\57\0\1\4"+
    "\57\0\1\5\57\0\1\6\56\0\1\50\1\51\3\0"+
    "\2\50\1\0\1\50\1\0\1\50\3\52\3\50\1\0"+
    "\25\50\12\0\1\53\65\0\1\54\1\0\3\21\53\0"+
    "\1\55\57\0\3\27\5\0\24\27\23\0\3\27\5\0"+
    "\16\27\1\56\5\27\23\0\3\27\5\0\11\27\1\57"+
    "\2\27\1\60\7\27\23\0\3\27\5\0\21\27\1\61"+
    "\2\27\23\0\1\27\1\62\1\63\5\0\24\27\23\0"+
    "\3\27\5\0\13\27\1\64\10\27\23\0\3\27\5\0"+
    "\4\27\1\65\17\27\23\0\3\27\5\0\14\27\1\66"+
    "\7\27\23\0\3\27\5\0\1\67\23\27\23\0\3\27"+
    "\5\0\4\27\1\70\17\27\23\0\3\27\5\0\2\27"+
    "\1\71\21\27\23\0\3\27\5\0\1\72\2\27\1\73"+
    "\1\74\2\27\1\75\1\76\5\27\1\77\5\27\2\0"+
    "\1\100\20\0\3\27\5\0\1\101\23\27\46\0\1\102"+
    "\45\0\1\103\31\0\1\50\1\51\3\0\2\50\1\0"+
    "\1\50\1\104\1\50\3\52\3\50\1\0\25\50\23\0"+
    "\3\105\54\0\3\27\5\0\1\106\23\27\23\0\3\27"+
    "\5\0\12\27\1\107\11\27\23\0\3\27\5\0\13\27"+
    "\1\110\10\27\23\0\3\27\5\0\10\27\1\111\13\27"+
    "\2\0\1\112\20\0\3\27\5\0\20\27\1\113\3\27"+
    "\23\0\3\27\5\0\12\27\1\114\11\27\23\0\3\27"+
    "\5\0\16\27\1\115\5\27\23\0\3\27\5\0\17\27"+
    "\1\116\4\27\3\0\1\117\17\0\3\27\5\0\14\27"+
    "\1\120\7\27\23\0\3\27\5\0\1\27\1\121\22\27"+
    "\23\0\3\27\5\0\23\27\1\122\23\0\3\27\5\0"+
    "\15\27\1\123\6\27\50\0\1\124\31\0\3\27\5\0"+
    "\16\27\1\125\5\27\43\0\1\112\15\0\1\112\44\0"+
    "\1\126\32\0\3\50\54\0\3\27\5\0\17\27\1\127"+
    "\4\27\3\0\1\130\17\0\3\27\5\0\4\27\1\131"+
    "\17\27\23\0\3\27\5\0\2\27\1\132\21\27\23\0"+
    "\3\27\5\0\2\27\1\133\21\27\35\0\1\134\44\0"+
    "\3\27\5\0\14\27\1\135\7\27\23\0\3\27\5\0"+
    "\1\27\1\136\22\27\23\0\3\27\5\0\1\137\23\27"+
    "\23\0\3\27\5\0\21\27\1\140\2\27\54\0\1\141"+
    "\25\0\3\27\5\0\16\27\1\142\5\27\23\0\3\27"+
    "\5\0\11\27\1\143\12\27\23\0\3\27\5\0\20\27"+
    "\1\144\3\27\23\0\3\27\5\0\14\27\1\145\7\27"+
    "\47\0\1\146\32\0\3\27\5\0\10\27\1\147\13\27"+
    "\2\0\1\150\46\0\1\151\30\0\3\27\5\0\4\27"+
    "\1\152\17\27\37\0\1\153\42\0\3\27\5\0\13\27"+
    "\1\154\10\27\23\0\3\27\5\0\10\27\1\155\13\27"+
    "\2\0\1\156\20\0\3\27\5\0\10\27\1\157\13\27"+
    "\2\0\1\160\40\0\1\160\15\0\1\160\20\0\3\27"+
    "\5\0\3\27\1\161\20\27\23\0\3\27\5\0\16\27"+
    "\1\162\5\27\23\0\3\27\5\0\12\27\1\163\11\27"+
    "\23\0\3\27\5\0\11\27\1\164\12\27\44\0\1\165"+
    "\35\0\3\27\5\0\4\27\1\166\17\27\23\0\3\27"+
    "\5\0\4\27\1\167\17\27\23\0\3\27\5\0\14\27"+
    "\1\170\7\27\23\0\3\27\5\0\1\171\23\27\33\0"+
    "\1\172\62\0\1\173\42\0\3\27\5\0\17\27\1\174"+
    "\4\27\3\0\1\175\46\0\1\175\7\0\1\175\17\0"+
    "\3\27\5\0\20\27\1\176\3\27\23\0\3\27\5\0"+
    "\14\27\1\177\7\27\47\0\1\200\32\0\3\27\5\0"+
    "\14\27\1\201\7\27\47\0\1\202\32\0\3\27\5\0"+
    "\14\27\1\203\7\27\23\0\3\27\5\0\4\27\1\204"+
    "\17\27\23\0\3\27\5\0\4\27\1\205\17\27\23\0"+
    "\3\27\5\0\20\27\1\206\3\27\53\0\1\207\26\0"+
    "\3\27\5\0\1\27\1\210\22\27\34\0\1\211\45\0"+
    "\3\27\5\0\1\212\23\27\23\0\3\27\5\0\13\27"+
    "\1\213\10\27\46\0\1\214\33\0\3\27\5\0\17\27"+
    "\1\215\4\27\3\0\1\216\17\0\3\27\5\0\20\27"+
    "\1\217\3\27\23\0\3\27\5\0\11\27\1\220\12\27"+
    "\44\0\1\221\35\0\3\27\5\0\16\27\1\222\5\27"+
    "\23\0\3\27\5\0\16\27\1\223\5\27\23\0\3\27"+
    "\5\0\4\27\1\224\17\27\37\0\1\225\42\0\3\27"+
    "\5\0\10\27\1\226\13\27\2\0\1\227\20\0\3\27"+
    "\5\0\14\27\1\230\7\27\23\0\3\27\5\0\17\27"+
    "\1\231\4\27\3\0\1\232\46\0\1\232\7\0\1\232"+
    "\17\0\3\27\5\0\14\27\1\233\7\27\47\0\1\234"+
    "\32\0\3\27\5\0\17\27\1\235\4\27\3\0\1\236"+
    "\17\0\3\27\5\0\17\27\1\237\4\27\3\0\1\240"+
    "\46\0\1\240\7\0\1\240";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5264];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\10\11\1\1\2\11\1\1\2\11"+
    "\15\1\2\11\2\1\1\0\1\11\1\0\1\11\1\0"+
    "\1\11\22\1\1\0\1\1\3\0\5\1\1\0\4\1"+
    "\1\0\4\1\1\0\1\1\1\0\1\1\1\0\3\1"+
    "\1\0\4\1\1\0\4\1\1\11\1\1\2\0\1\1"+
    "\1\0\2\1\1\0\1\1\1\0\4\1\1\0\4\1"+
    "\1\0\1\11\1\1\1\11\2\1\1\0\1\1\1\11"+
    "\4\1\1\11\1\1\1\0\2\1\1\11\1\1\1\11"+
    "\2\1\1\0\3\1\1\0\1\1\1\0\2\1\1\11"+
    "\1\1\1\0\1\1\1\11\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private ArrayList<String> errores = new ArrayList<>();

    public void setErrores(ArrayList<String> errores) {
        this.errores = errores;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCiclo(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolos.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errores.add("Error Lexico: | Lexema: " + yytext() + " | Linea: " + (yyline+1) + " | Columna: " + (yycolumn+1));;return new Symbol(Simbolos.ERROR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 43: break;
          case 2:
            { /*ignorar*/
            }
            // fall through
          case 44: break;
          case 3:
            { return new Symbol(Simbolos.PARENTESIS_A, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 45: break;
          case 4:
            { return new Symbol(Simbolos.PARENTESIS_C, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 46: break;
          case 5:
            { return new Symbol(Simbolos.MULTIPLICACION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 47: break;
          case 6:
            { return new Symbol(Simbolos.SUMA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 48: break;
          case 7:
            { return new Symbol(Simbolos.COMA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 49: break;
          case 8:
            { return new Symbol(Simbolos.RESTA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 50: break;
          case 9:
            { return new Symbol(Simbolos.PUNTO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 51: break;
          case 10:
            { return new Symbol(Simbolos.DIVISION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 52: break;
          case 11:
            { return new Symbol(Simbolos.ENTERO, yyline+1, yycolumn+1, Integer.parseInt(yytext()));
            }
            // fall through
          case 53: break;
          case 12:
            { return new Symbol(Simbolos.DOS_PUNTOS, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 54: break;
          case 13:
            { return new Symbol(Simbolos.PUNTO_COMA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 55: break;
          case 14:
            { return new Symbol(Simbolos.ETIQUETA_ABRIR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 56: break;
          case 15:
            { return new Symbol(Simbolos.SIGNO_IGUAL, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 57: break;
          case 16:
            { return new Symbol(Simbolos.ETIQUETA_CERRAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 58: break;
          case 17:
            { return new Symbol(Simbolos.ID, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 59: break;
          case 18:
            { return new Symbol(Simbolos.CORCHETE_A, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 60: break;
          case 19:
            { return new Symbol(Simbolos.CORCHETE_C, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 61: break;
          case 20:
            { return new Symbol(Simbolos.CADENA, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 62: break;
          case 21:
            { return new Symbol(Simbolos.DOLAR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 63: break;
          case 22:
            { return new Symbol(Simbolos.ETIQUETA_FIN, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 64: break;
          case 23:
            { return new Symbol(Simbolos.BR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 65: break;
          case 24:
            { return new Symbol(Simbolos.H1, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 66: break;
          case 25:
            { return new Symbol(Simbolos.H2, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 67: break;
          case 26:
            { return new Symbol(Simbolos.TD, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 68: break;
          case 27:
            { return new Symbol(Simbolos.TH, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 69: break;
          case 28:
            { return new Symbol(Simbolos.TR, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 70: break;
          case 29:
            { return new Symbol(Simbolos.DECIMAL, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 71: break;
          case 30:
            { return new Symbol(Simbolos.TIPO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 72: break;
          case 31:
            { return new Symbol(Simbolos.SCORE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 73: break;
          case 32:
            { return new Symbol(Simbolos.TABLE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 74: break;
          case 33:
            { return new Symbol(Simbolos.TEXTO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 75: break;
          case 34:
            { return new Symbol(Simbolos.CLASES, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 76: break;
          case 35:
            { return new Symbol(Simbolos.INICIO, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 77: break;
          case 36:
            { return new Symbol(Simbolos.NOMBRE, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 78: break;
          case 37:
            { return new Symbol(Simbolos.RESULT, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 79: break;
          case 38:
            { return new Symbol(Simbolos.FUNCION, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 80: break;
          case 39:
            { return new Symbol(Simbolos.METODOS, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 81: break;
          case 40:
            { return new Symbol(Simbolos.VARIABLES, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 82: break;
          case 41:
            { return new Symbol(Simbolos.PARAMETROS, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 83: break;
          case 42:
            { return new Symbol(Simbolos.COMENTARIOS, yyline+1, yycolumn+1, yytext());
            }
            // fall through
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   */
  private static String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = Simbolos.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java LexerCiclo [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        LexerCiclo scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new LexerCiclo(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
