
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package reporte.ciclo;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int PARAMETROS = 11;
  public static final int TIPO = 9;
  public static final int NOMBRE = 8;
  public static final int ENTERO = 37;
  public static final int FUNCION = 10;
  public static final int SCORE = 3;
  public static final int ETIQUETA_FIN = 28;
  public static final int RESTA = 22;
  public static final int COMENTARIOS = 7;
  public static final int CORCHETE_C = 31;
  public static final int CORCHETE_A = 30;
  public static final int SUMA = 21;
  public static final int CLASES = 4;
  public static final int ID = 35;
  public static final int EOF = 0;
  public static final int DECIMAL = 20;
  public static final int TABLE = 15;
  public static final int error = 1;
  public static final int CADENA = 36;
  public static final int BR = 19;
  public static final int ETIQUETA_CERRAR = 29;
  public static final int ERROR = 34;
  public static final int METODOS = 6;
  public static final int TR = 16;
  public static final int VARIABLES = 5;
  public static final int PUNTO = 32;
  public static final int PARENTESIS_C = 27;
  public static final int PARENTESIS_A = 26;
  public static final int TH = 18;
  public static final int ETIQUETA_ABRIR = 25;
  public static final int TD = 17;
  public static final int INICIO = 2;
  public static final int TEXTO = 12;
  public static final int DIVISION = 24;
  public static final int H2 = 14;
  public static final int RESULT = 33;
  public static final int H1 = 13;
  public static final int MULTIPLICACION = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "SCORE",
  "CLASES",
  "VARIABLES",
  "METODOS",
  "COMENTARIOS",
  "NOMBRE",
  "TIPO",
  "FUNCION",
  "PARAMETROS",
  "TEXTO",
  "H1",
  "H2",
  "TABLE",
  "TR",
  "TD",
  "TH",
  "BR",
  "DECIMAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "ETIQUETA_ABRIR",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "ETIQUETA_FIN",
  "ETIQUETA_CERRAR",
  "CORCHETE_A",
  "CORCHETE_C",
  "PUNTO",
  "RESULT",
  "ERROR",
  "ID",
  "CADENA",
  "ENTERO"
  };
}

