
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LOGICO_IGUAL = 33;
  public static final int CHAR = 7;
  public static final int ENTERO = 29;
  public static final int CASE = 16;
  public static final int RESTA = 42;
  public static final int DOUBLE = 8;
  public static final int DOS_PUNTOS = 47;
  public static final int PRIVATE = 19;
  public static final int CORCHETE_C = 52;
  public static final int INT = 4;
  public static final int CORCHETE_A = 51;
  public static final int LLAVE_C = 50;
  public static final int LOGICO_Y = 37;
  public static final int LLAVE_A = 49;
  public static final int FOR = 12;
  public static final int SIGNO_IGUAL = 53;
  public static final int LOGICO_O = 38;
  public static final int OBJECT = 9;
  public static final int LETRA = 32;
  public static final int LOGICO_DISTINTO = 34;
  public static final int CLASS = 3;
  public static final int INCREMENTO = 39;
  public static final int SUMA = 41;
  public static final int IF = 10;
  public static final int THIS = 24;
  public static final int PUNTO_COMA = 48;
  public static final int ID = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int DECIMAL = 28;
  public static final int RETURN = 22;
  public static final int TRUE = 25;
  public static final int DECREMENTO = 40;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int COMA = 54;
  public static final int CADENA = 31;
  public static final int MENOR = 55;
  public static final int BREAK = 21;
  public static final int VOID = 23;
  public static final int ERROR = 58;
  public static final int SWITCH = 15;
  public static final int MAYOR = 56;
  public static final int IMPORT = 2;
  public static final int ELSE = 11;
  public static final int PUNTO = 57;
  public static final int PROTECTED = 18;
  public static final int PARENTESIS_C = 46;
  public static final int FINAL = 20;
  public static final int WHILE = 13;
  public static final int PARENTESIS_A = 45;
  public static final int MAYOR_IGUAL = 36;
  public static final int PUBLIC = 17;
  public static final int STRING = 6;
  public static final int MENOR_IGUAL = 35;
  public static final int FALSE = 26;
  public static final int DIVISION = 44;
  public static final int DO = 14;
  public static final int MULTIPLICACION = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IMPORT",
  "CLASS",
  "INT",
  "BOOLEAN",
  "STRING",
  "CHAR",
  "DOUBLE",
  "OBJECT",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "SWITCH",
  "CASE",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "FINAL",
  "BREAK",
  "RETURN",
  "VOID",
  "THIS",
  "TRUE",
  "FALSE",
  "NEW",
  "DECIMAL",
  "ENTERO",
  "ID",
  "CADENA",
  "LETRA",
  "LOGICO_IGUAL",
  "LOGICO_DISTINTO",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "LOGICO_Y",
  "LOGICO_O",
  "INCREMENTO",
  "DECREMENTO",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "SIGNO_IGUAL",
  "COMA",
  "MENOR",
  "MAYOR",
  "PUNTO",
  "ERROR"
  };
}

