
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package jison.analisis.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int METODOS = 5;
  public static final int DECIMAL = 12;
  public static final int ERROR = 20;
  public static final int SCORE = 2;
  public static final int ID = 21;
  public static final int DOS_PUNTOS = 14;
  public static final int TIPO = 8;
  public static final int COMA = 19;
  public static final int VARIABLES = 4;
  public static final int COMENTARIOS = 6;
  public static final int NOMBRE = 7;
  public static final int EOF = 0;
  public static final int PARAMETROS = 10;
  public static final int COMILLA = 13;
  public static final int TEXTO = 11;
  public static final int error = 1;
  public static final int LLAVE_C = 16;
  public static final int CLASES = 3;
  public static final int LLAVE_A = 15;
  public static final int ENTERO = 23;
  public static final int COMENTARIO = 22;
  public static final int CORCHETE_C = 18;
  public static final int CORCHETE_A = 17;
  public static final int FUNCION = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SCORE",
  "CLASES",
  "VARIABLES",
  "METODOS",
  "COMENTARIOS",
  "NOMBRE",
  "TIPO",
  "FUNCION",
  "PARAMETROS",
  "TEXTO",
  "DECIMAL",
  "COMILLA",
  "DOS_PUNTOS",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "COMA",
  "ERROR",
  "ID",
  "COMENTARIO",
  "ENTERO"
  };
}

